### ISSUE TITLE
Question with regard to `0z`

### ISSUE THREAD

**Issue by suminb** [suminb/base62#12]
Someone sent me an email asking this question:

> I see your base62 script at github https://github.com/suminb/base62/blob/develop/base62.py, it's a awesome project and save me lots of time. But I have a question about the code
>
> ```python
> def decode(b):
>     """Decodes a base62 encoded value ``b``."""
>
>     if b.startswith('0z'):
>         b = b[2:]
>
>     l, i, v = len(b), 0, 0
>     for x in b:
>         v += _value(x) * (BASE ** (l - (i + 1)))
>         i += 1
>
>     return v
> ```
>
> About the above code, what does the `if b.startswith('0z')` do ? why there need to do this? I don't understand. Thanks.

This is a great question, in fact, and I would like to share this question along with my answer with everyone else.

The prefix `0z` is something that I used to use in my old code. It was a decade ago or so. At that time I wanted to use different encodings within a single project. For example,

- `123456` (decimal)
- `0xf10a` (hexadecimal)
- `0zExid` (base62)

were all in use. The code for checking for the prefix `0z` is there merely for backward-compatibility reasons and not necessary in ordinary cases. If you ask `base62` to encode an integer, it will not add the prefix `0z`. Likewise, if you ask to decode a base62 string without the prefix, it will work fine.

P.S. It is generally okay to send me an email, but I highly recommend to post your question on GitHub for two reasons:

1. Our discussion becomes sharable and searchable, and everyone benefits from it.
2. Someone else may be able to answer quicker than me.

**Comment by wd** [comment]
Thanks for your reply, maybe I misunderstand what is the 'issue' mean, cause this question is not mean I found a problem about your code, I also have checked your commit, this line was added at the first day, so I think maybe it was something that I have not learned. :)
