### ISSUE TITLE
Wheels to PyPI

### ISSUE THREAD

**Issue by falexwolf** [suminb/base62#20]
Thank you for the great package, @suminb!

Would you consider publishing wheels beyond the source on PyPI for faster installation? This is, in particular, relevant for projects with long lists of dependencies with small packages like this one. 😅

**Comment by suminb** [comment]
Thanks for your suggestion! I've just pushed a `.whl` file, which is available on https://pypi.org/project/pybase62/#files. Sorry for the late response.

**Comment by falexwolf** [comment]
Thank you, and awesome!
