### ISSUE TITLE
Use package to base62 encode binary data

### ISSUE THREAD

**Issue by dhimmel** [suminb/base62#4]
I'm interested in base62 encoding the bytes digest of a hash: https://github.com/greenelab/deep-review/pull/298.

It looks like `base62.encode()` takes an`int` not a `bytes` object. I assume the solution is to convert the bytes object to an `int`. @suminb do you have a suggestion for the best method to use?

**Comment by dhimmel** [comment]
It looks like [`int.from_bytes`](https://docs.python.org/3/library/stdtypes.html#int.from_bytes) is the way to go. There are choices for `byteorder` and `signed`.

**Comment by suminb** [comment]
`int.from_bytes` looks promising, but I'm not sure what the performance implications would be if a large byte array is given. Say, a metabyte in size, for example. Any opinion on this?

**Comment by dhimmel** [comment]
> I'm not sure what the performance implications would be if a large byte array is given. Say, a metabyte in size, for example. Any opinion on this?

That's not a concern for my use case, which will be encoding only 5-10 bytes. In the worst case, I assume it won't be worse than the base62 encoding... so you're at most doubling the runtime?

**Comment by suminb** [comment]
I see. In that case, we could provide another function that accepts a byte array to pass it to `encode()`. As a precaution, it would be great if a warning message is shown when a large array is given. I'm thinking something like this:

    def encode_bytes(array):
        if len(array) > (some threshold):
            warnings.warn('This will be slow')

        return encode(int.from_bytes(array))

**Comment by dhimmel** [comment]
> we could provide another function that accepts a byte array to pass it to encode()

@suminb I think this would greatly increase the utility of the library.

The function should probably accept [binary sequence types](https://docs.python.org/3.6/library/stdtypes.html#binaryseq). `int.from_bytes` doesn't exist in Python 2. I personally don't care about Python 2 compatibility... but I don't know what direction you'd like to take the repo.

I'm also not very familiar with binary data and encodings. It would be ideal if the base62 encoding of binary data here produces the same results as other encoders. Will it follow the same approach as the builtin base encodings of binary data (such as base64 or base32). Here's the Python source code if it helps:

+ https://github.com/python/cpython/blob/3.6/Lib/base64.py
+ https://github.com/python/cpython/blob/master/Modules/binascii.c

**Comment by suminb** [comment]
Agreed. This will definitely be a notable improvement. However, it's getting late (almost 1am over here), so I'll look into this tomorrow. Thanks for your interest in this project.
